-- MySQL Script generated by MySQL Workbench
-- Tue Nov 17 09:38:07 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Personne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Personne` (
  `idPersonne` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  PRIMARY KEY (`idPersonne`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professeur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professeur` (
  `id` INT NOT NULL,
  `prenom` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  `Personne_idPersonne` INT NOT NULL,
  PRIMARY KEY (`id`, `Personne_idPersonne`),
  INDEX `fk_professeur_Personne1_idx` (`Personne_idPersonne` ASC) VISIBLE,
  CONSTRAINT `fk_professeur_Personne1`
    FOREIGN KEY (`Personne_idPersonne`)
    REFERENCES `mydb`.`Personne` (`idPersonne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`salle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`salle` (
  `idsalle` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idsalle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cours` (
  `idcours` INT NOT NULL,
  `debut` DATETIME NULL,
  `fin` DATETIME NULL,
  `salle_idsalle` INT NOT NULL,
  `professeur_id` INT NOT NULL,
  `professeur_Personne_idPersonne` INT NOT NULL,
  PRIMARY KEY (`idcours`),
  INDEX `fk_cours_salle1_idx` (`salle_idsalle` ASC) VISIBLE,
  INDEX `fk_cours_professeur1_idx` (`professeur_id` ASC, `professeur_Personne_idPersonne` ASC) VISIBLE,
  CONSTRAINT `fk_cours_salle1`
    FOREIGN KEY (`salle_idsalle`)
    REFERENCES `mydb`.`salle` (`idsalle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cours_professeur1`
    FOREIGN KEY (`professeur_id` , `professeur_Personne_idPersonne`)
    REFERENCES `mydb`.`professeur` (`id` , `Personne_idPersonne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Adressse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Adressse` (
  `idAdressse` INT NOT NULL,
  `rue` VARCHAR(45) NULL,
  `numéro` INT NULL,
  `ville` VARCHAR(45) NULL,
  PRIMARY KEY (`idAdressse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`etudiant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`etudiant` (
  `diplome` VARCHAR(45) NULL,
  `Personne_idPersonne` INT NOT NULL,
  `Adressse_idAdressse` INT NOT NULL,
  `Adressse_idAdressse1` INT NOT NULL,
  PRIMARY KEY (`Personne_idPersonne`, `Adressse_idAdressse`),
  INDEX `fk_etudiant_Adressse1_idx` (`Adressse_idAdressse1` ASC) VISIBLE,
  CONSTRAINT `fk_etudiant_Adressse1`
    FOREIGN KEY (`Adressse_idAdressse1`)
    REFERENCES `mydb`.`Adressse` (`idAdressse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Participant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Participant` (
  `idParticipant` INT NOT NULL,
  `place` VARCHAR(45) NULL,
  `etudiant_Personne_idPersonne` INT NOT NULL,
  `etudiant_Adressse_idAdressse` INT NOT NULL,
  `cours_idcours` INT NOT NULL,
  PRIMARY KEY (`idParticipant`),
  INDEX `fk_Participant_etudiant1_idx` (`etudiant_Personne_idPersonne` ASC, `etudiant_Adressse_idAdressse` ASC) VISIBLE,
  INDEX `fk_Participant_cours1_idx` (`cours_idcours` ASC) VISIBLE,
  CONSTRAINT `fk_Participant_etudiant1`
    FOREIGN KEY (`etudiant_Personne_idPersonne` , `etudiant_Adressse_idAdressse`)
    REFERENCES `mydb`.`etudiant` (`Personne_idPersonne` , `Adressse_idAdressse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Participant_cours1`
    FOREIGN KEY (`cours_idcours`)
    REFERENCES `mydb`.`cours` (`idcours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
